function safeObj(schema) {
  return z.union([schema, z.null(), z.undefined()]).transform(v => (v && typeof v === 'object' ? v : {}));
}

export const Schema = z.object({
  系统: safeObj(z.object({
    积分: z.coerce.number().prefault(0),
    今日签到积分: z.coerce.number().prefault(8),
    今日任务: z.boolean().prefault(false),
    当前日期: z.string().prefault(''),
    系统任务内容: z.string().prefault('到西院杂务房报到，熟悉宗门环境'),
    系统任务进度: z.coerce.number().prefault(0),
    系统任务奖励: z.string().prefault(''),
    宗门任务内容: z.string().prefault(''),
    宗门任务进度: z.coerce.number().prefault(0),
    宗门任务奖励: z.string().prefault(''),
    宗门任务待提交: z.boolean().prefault(false),
  })),
  主角: safeObj(z.object({
    姓名: z.string().prefault(''),
    年龄: z.coerce.number().prefault(16),
    性别: z.string().prefault(''),
    灵石: z.coerce.number().prefault(0),
    寿元: z.coerce.number().prefault(100),
    身体强化: z.object({
      力量: z.coerce.number().transform(v => _.clamp(v, 1, 100)).prefault(1),
      速度: z.coerce.number().transform(v => _.clamp(v, 1, 100)).prefault(1),
      防御: z.coerce.number().transform(v => _.clamp(v, 1, 100)).prefault(1),
      抗性: z.coerce.number().transform(v => _.clamp(v, 1, 100)).prefault(1),
    }).prefault({}),
    属性: z.object({
      长度: z.coerce.number().transform(v => _.clamp(v, 0, 25)).prefault(10),
      粗度: z.coerce.number().transform(v => _.clamp(v, 0, 5)).prefault(3),
      硬度: z.coerce.number().transform(v => _.clamp(v, 0, 5)).prefault(3),
      耐久度: z.coerce.number().transform(v => _.clamp(v, 0, 60)).prefault(30),
      精液量: z.coerce.number().transform(v => _.clamp(v, 100, 250)).prefault(100),
    }).prefault({}),
    道具: z.array(z.string()).prefault([]),
    丹药: z.array(z.string()).prefault([]),
    法宝: z.array(z.string()).prefault([]),
    武器: z.array(z.string()).prefault([]),
    功法: z.array(z.string()).prefault([]),
    衣服: z.array(z.string()).prefault([]),
    杂物: z.array(z.string()).prefault([]),
    技能: z.object({
      NSFW技能: z.array(z.string()).prefault([]),
      修为技能: z.array(z.string()).prefault([]),
      生活技能: z.array(z.string()).prefault([]),
    }).prefault({}),
  })),
  NPC关系: z.record(z.object({
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 300)).prefault(5),
    沉沦: z.coerce.number().transform(v => _.clamp(v, 0, 300)).prefault(0),
    性别: z.string().prefault(''),
    描述: z.string().prefault(''),
    年纪: z.coerce.number().prefault(0),
    修为: z.string().prefault(''),
    灵根: z.string().prefault(''),
    小境界: z.coerce.number().transform(v => _.clamp(v, 1, 9)).prefault(1),
    修为进度: z.coerce.number().prefault(0),
    瓶颈: z.boolean().prefault(false),
    寿元: z.coerce.number().prefault(150),
    所属宗门: z.string().prefault(''),
    职位: z.string().prefault(''),
  })).prefault({}),
  当前互动NPC: z.string().prefault(''),
  当前场景NPC: z.array(z.string()).prefault([]),
  当前宗门: z.object({
    名称: z.string().prefault(''),
    品级: z.string().prefault(''),
    介绍: z.string().prefault(''),
    掌门: z.string().prefault(''),
    掌门修为: z.string().prefault(''),
    长老: z.array(z.string()).prefault([]),
    太上长老: z.array(z.string()).prefault([]),
    亲传: z.array(z.string()).prefault([]),
    核心: z.coerce.number().prefault(0),
    内门: z.coerce.number().prefault(0),
    外门: z.coerce.number().prefault(0),
  }).prefault({}),
});
export type Schema = z.output<typeof Schema>;
